name: Build and Release Marketplace Database

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build-db:
    name: Build Marketplace DB
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: 1. Create Database Schema
        run: python src/create_db.py --db-path ./marketplace.db

      # --- ADD THIS STEP ---
      - name: 1.5. Update Build Info Table
        run: |
          BUILD_TIMESTAMP=$(date --iso-8601=seconds) # Get UTC timestamp
          python src/update_build_info.py \
            --db-path ./marketplace.db \
            --tag "${{ github.event.release.tag_name }}" \
            --commit-sha "${{ github.sha }}" \
            --timestamp "$BUILD_TIMESTAMP"
      # --- END OF ADDED STEP ---

      - name: 2. Load Catalogs from YAML
        run: python src/load_yaml.py --db-path ./marketplace.db --yaml-path ./catalogs.yaml

      - name: 3. Load Cabinets from Catalogs (Downloads CSVs)
        run: python src/load_cabinets.py --db-path ./marketplace.db

      - name: Verify Database File Exists
        run: |
          if [ -f ./marketplace.db ]; then
            echo "marketplace.db successfully created."
            ls -lh ./marketplace.db
          else
            echo "Error: marketplace.db not found after scripts execution!"
            exit 1
          fi

      - name: Upload Release Asset (marketplace.db)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./marketplace.db
          asset_name: marketplace.db
          asset_content_type: application/vnd.sqlite3